# Generated by Django 3.2.12 on 2024-03-07 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivitySummary',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('slug', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TimeSeriesPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='GPT',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('slug', models.CharField(max_length=255)),
                ('generated_date', models.DateTimeField()),
                ('description', models.TextField()),
                ('frameworks', models.CharField(max_length=255)),
                ('featured', models.BooleanField(default=False)),
                ('tryitout_link', models.CharField(default='', max_length=255)),
                ('activity_summary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gpts.activitysummary')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gpts.owner')),
                ('tags', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gpts.tags')),
            ],
        ),
        migrations.AddField(
            model_name='activitysummary',
            name='upvotes',
            field=models.ManyToManyField(related_name='upvotes', to='gpts.TimeSeriesPoint'),
        ),
        migrations.AddField(
            model_name='activitysummary',
            name='views',
            field=models.ManyToManyField(related_name='views', to='gpts.TimeSeriesPoint'),
        ),
    ]
