# Generated by Django 3.2.12 on 2024-03-05 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivitySummary',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('generatedDate', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ModelStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('value', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('slug', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TimeSeriesPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='GPT',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('slug', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('frameworks', models.CharField(max_length=255)),
                ('featured', models.BooleanField(default=False)),
                ('tryitout_link', models.CharField(default='', max_length=255)),
                ('activitySummary', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gpts.activitysummary')),
                ('categories', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gpts.category')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gpts.owner')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='tags',
            field=models.ManyToManyField(to='gpts.Tags'),
        ),
        migrations.AddField(
            model_name='activitysummary',
            name='modelStats',
            field=models.ManyToManyField(to='gpts.ModelStats'),
        ),
        migrations.AddField(
            model_name='activitysummary',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gpts.owner'),
        ),
        migrations.AddField(
            model_name='activitysummary',
            name='tags',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gpts.tags'),
        ),
        migrations.AddField(
            model_name='activitysummary',
            name='upvotes',
            field=models.ManyToManyField(related_name='upvotes', to='gpts.TimeSeriesPoint'),
        ),
        migrations.AddField(
            model_name='activitysummary',
            name='views',
            field=models.ManyToManyField(related_name='views', to='gpts.TimeSeriesPoint'),
        ),
    ]
