# Generated by Django 3.2.12 on 2024-03-05 08:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gpts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivitySummary',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('generated_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('full_path', models.CharField(max_length=255)),
                ('listing_url', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='GPT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('time_series', models.JSONField()),
                ('downloads', models.JSONField()),
                ('title', models.CharField(max_length=255)),
                ('views', models.JSONField()),
                ('categories', models.JSONField()),
                ('dataset_count', models.IntegerField()),
                ('competition_count', models.IntegerField()),
                ('notebook_count', models.IntegerField()),
                ('display_name', models.CharField(max_length=255)),
                ('model_count', models.IntegerField()),
                ('type', models.CharField(max_length=255)),
                ('frameworks', models.JSONField()),
                ('activity_summary', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gpts.activitysummary')),
            ],
        ),
        migrations.CreateModel(
            name='ModelStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('value', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='GPTModel',
        ),
        migrations.AddField(
            model_name='gpt',
            name='model_stats',
            field=models.ManyToManyField(to='gpts.ModelStat'),
        ),
        migrations.AddField(
            model_name='gpt',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gpt',
            name='points',
            field=models.ManyToManyField(to='gpts.Point'),
        ),
        migrations.AddField(
            model_name='gpt',
            name='tags',
            field=models.ManyToManyField(to='gpts.Tag'),
        ),
    ]
