# Generated by Django 3.2.12 on 2024-03-07 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gpt',
            name='tags',
        ),
        migrations.AddField(
            model_name='gpt',
            name='tags',
            field=models.ManyToManyField(null=True, to='gpts.Tags'),
        ),
    ]
