# Generated by Django 3.2.12 on 2024-03-05 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gpts', '0002_auto_20240305_0858'),
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('slug', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('fullPath', models.CharField(max_length=255)),
                ('listingUrl', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('datasetCount', models.IntegerField()),
                ('competitionCount', models.IntegerField()),
                ('notebookCount', models.IntegerField()),
                ('displayName', models.CharField(max_length=255)),
                ('modelCount', models.IntegerField()),
            ],
        ),
        migrations.RenameModel(
            old_name='ModelStat',
            new_name='ModelStats',
        ),
        migrations.RenameModel(
            old_name='Point',
            new_name='TimeSeriesPoint',
        ),
        migrations.RenameField(
            model_name='activitysummary',
            old_name='generated_date',
            new_name='generatedDate',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='full_path',
            new_name='type',
        ),
        migrations.RenameField(
            model_name='gpt',
            old_name='activity_summary',
            new_name='activitySummary',
        ),
        migrations.RemoveField(
            model_name='category',
            name='listing_url',
        ),
        migrations.RemoveField(
            model_name='category',
            name='name',
        ),
        migrations.RemoveField(
            model_name='gpt',
            name='competition_count',
        ),
        migrations.RemoveField(
            model_name='gpt',
            name='dataset_count',
        ),
        migrations.RemoveField(
            model_name='gpt',
            name='display_name',
        ),
        migrations.RemoveField(
            model_name='gpt',
            name='downloads',
        ),
        migrations.RemoveField(
            model_name='gpt',
            name='model_count',
        ),
        migrations.RemoveField(
            model_name='gpt',
            name='model_stats',
        ),
        migrations.RemoveField(
            model_name='gpt',
            name='notebook_count',
        ),
        migrations.RemoveField(
            model_name='gpt',
            name='points',
        ),
        migrations.RemoveField(
            model_name='gpt',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='gpt',
            name='time_series',
        ),
        migrations.RemoveField(
            model_name='gpt',
            name='title',
        ),
        migrations.RemoveField(
            model_name='gpt',
            name='type',
        ),
        migrations.RemoveField(
            model_name='gpt',
            name='views',
        ),
        migrations.AddField(
            model_name='activitysummary',
            name='downloads',
            field=models.ManyToManyField(related_name='downloads', to='gpts.TimeSeriesPoint'),
        ),
        migrations.AddField(
            model_name='activitysummary',
            name='modelStats',
            field=models.ManyToManyField(to='gpts.ModelStats'),
        ),
        migrations.AddField(
            model_name='activitysummary',
            name='views',
            field=models.ManyToManyField(related_name='views', to='gpts.TimeSeriesPoint'),
        ),
        migrations.AlterField(
            model_name='gpt',
            name='categories',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gpts.category'),
        ),
        migrations.AlterField(
            model_name='gpt',
            name='frameworks',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='gpt',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.AddField(
            model_name='activitysummary',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gpts.owner'),
        ),
        migrations.AddField(
            model_name='activitysummary',
            name='tags',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gpts.tags'),
        ),
        migrations.AddField(
            model_name='category',
            name='tags',
            field=models.ManyToManyField(to='gpts.Tags'),
        ),
        migrations.AlterField(
            model_name='gpt',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gpts.owner'),
        ),
    ]
