# Generated by Django 3.2.12 on 2024-03-07 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpts', '0002_auto_20240307_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gpt',
            name='tags',
            field=models.ManyToManyField(blank=True, to='gpts.Tags'),
        ),
    ]
