# Generated by Django 3.2.12 on 2024-03-07 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gpts', '0003_alter_gpt_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gpt',
            name='activity_summary',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='gpts.activitysummary'),
        ),
    ]
