# Generated by Django 3.2.12 on 2024-03-05 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gpts', '0003_auto_20240305_0918'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tags',
            name='competitionCount',
        ),
        migrations.RemoveField(
            model_name='tags',
            name='datasetCount',
        ),
        migrations.RemoveField(
            model_name='tags',
            name='description',
        ),
        migrations.RemoveField(
            model_name='tags',
            name='displayName',
        ),
        migrations.RemoveField(
            model_name='tags',
            name='fullPath',
        ),
        migrations.RemoveField(
            model_name='tags',
            name='listingUrl',
        ),
        migrations.RemoveField(
            model_name='tags',
            name='modelCount',
        ),
        migrations.RemoveField(
            model_name='tags',
            name='notebookCount',
        ),
    ]
