# Generated by Django 5.0.3 on 2024-03-07 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpts', '0004_alter_gpt_activity_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='gpt',
            name='total_upvote',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gpt',
            name='total_view',
            field=models.IntegerField(default=0),
        ),
    ]
